#
# This file contains configuration flags to customize your site
#

name: DrSchimke
author: Sascha Schimke
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.gravatar.com/avatar/63e3b9b25c5232fbad101d263354c94d.png

#
# Flags below are optional
#

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: DrSchimke
  instagram:
  linkedin:
  pinterest:
  rss: true
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

disqus:
google_analytics: UA-59380184-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title.html

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
